channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake-minimal =9.13.7
  - jinja2 =3.1.6
  - networkx =3.5
  - matplotlib =3.10.6
  - graphviz =13.1.2
  - pandas =2.3.2
  - pygments =2.19.1
  - snakemake-executor-plugin-slurm=2.0.0
